version: '3'
services:
  ordersdb:
    image: 'postgres:12'
    env_file:
      - ./db/ordersdb/db.env
    ports:
      - '5432:5432'
    volumes:
      - ./db/ordersdb/db_data:/var/lib/postgresql/data
  orders:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - '3001:3001'
    depends_on:
      - ordersdb
