name: CICD
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.4]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: pre-build checks
      run: |
        npm ci
        npm test
    - name: get aws
      uses: chrislennon/action-aws-cli@v1.1
    - run: docker build . --file Dockerfile --tag docker.pkg.github.com/abdalim/zetel-orders-service/zetel-orders-service:latest
    - run: docker push docker.pkg.github.com/abdalim/zetel-orders-service/zetel-orders-service:latest