name: CICD
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.4]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pre-build checks
      run: |
        npm ci
        npm test
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: zetel-orders-service
        tag: latest